export const userColumns = [
  { field: "id", headerName: "ID", width: 70 },
  {
    field: "user",
    headerName: "User",
    width: 230,
    renderCell: (params) => {
      return (
        <div>
          <span>{params.row.firstName}</span>
          <span>{params.row.lastName}</span>
        </div>
      );
    },
  },
  { field: "location", headerName: "Location", width: 100 },

  { field: "email", headerName: "Email", width: 100 },
  { field: "phoneNo", headerName: "ContactNo", width: 100 },

  { field: "favCategory", headerName: "FavCategory", width: 390 },
  {
    field: "status",
    headerName: "Status",
    width: 100,
    renderCell: (params) => {
      return <div className="cellwithstatus">{params.row.status}</div>;
    },
  },
];

export const userRows = [
  {
    id: 1,
    firstName: "sam",
    lastName: "hike",
    email: "email@hjsl",
    phoneNo: "23412313",
    location: "IND",
    favCategory: '["Technology","Sports","Business","Health","World"]',
    friends: null,
    followers: null,
    blocked: null,
    status: "Online",
  },
  {
    id: 2,
    firstName: "cam",
    lastName: "nemo",
    email: "email@hjsl",
    phoneNo: "23412313",
    location: "IND",
    favCategory: '["Technology","Sports","Business","Health","World"]',
    friends: "fi",
    followers: "fo",
    blocked: null,
    status: "Online",
  },
  {
    id: 3,
    firstName: "cam",
    lastName: "nemo",
    email: "email@hjsl",
    phoneNo: "23412313",
    location: "IND",
    favCategory: '["Technology","Sports","Business","Health","World"]',
    friends: null,
    followers: null,
    blocked: null,
    status: "Online",
  },
  {
    id: 4,
    firstName: "cam",
    lastName: "nemo",
    email: "email@hjsl",
    phoneNo: "23412313",
    location: "IND",
    favCategory: '["Technology","Sports","Business","Health","World"]',
    friends: null,
    followers: null,
    blocked: null,
    status: "Offline",
  },
  {
    id: 5,
    firstName: "sam",
    lastName: "nemo",
    email: "email@hjsl",
    phoneNo: "23412313",
    location: "IND",
    favCategory: '["Technology","Sports","Business","Health","World"]',
    friends: null,
    followers: null,
    blocked: null,
    status: "Online",
  },
  {
    id: 6,
    firstName: "sam",
    lastName: "hike",
    email: "email@hjsl",
    phoneNo: "23412313",
    location: "IND",
    favCategory: '["Technology","Sports","Business","Health","World"]',
    friends: null,
    followers: null,
    blocked: null,
    status: "Online",
  },
  {
    id: 7,
    firstName: "cam",
    lastName: "nemo",
    email: "email@hjsl",
    phoneNo: "23412313",
    location: "IND",
    favCategory: '["Technology","Sports","Business","Health","World"]',
    friends: "fi",
    followers: "fo",
    blocked: null,
    status: "Online",
  },
  {
    id: 8,
    firstName: "cam",
    lastName: "nemo",
    email: "email@hjsl",
    phoneNo: "23412313",
    location: "IND",
    favCategory: '["Technology","Sports","Business","Health","World"]',
    friends: null,
    followers: null,
    blocked: null,
    status: "Online",
  },
  {
    id: 9,
    firstName: "cam",
    lastName: "nemo",
    email: "email@hjsl",
    phoneNo: "23412313",
    location: "IND",
    favCategory: '["Technology","Sports","Business","Health","World"]',
    friends: null,
    followers: null,
    blocked: null,
    status: "Offline",
  },
  {
    id: 10,
    firstName: "sam",
    lastName: "nemo",
    email: "email@hjsl",
    phoneNo: "23412313",
    location: "IND",
    favCategory: '["Technology","Sports","Business","Health","World"]',
    friends: null,
    followers: null,
    blocked: null,
    status: "Online",
  },
];
